### ISSUE TITLE
Permission issue when trying deleting old git hook

### ISSUE THREAD

**Issue by jiachen247** [qgadrian/elixir_git_hooks#11]
Hi, thanks for maintining this library for us all to use!!

There seems to be a bug with permissions introduced in 7655a940b989de42cae7b62cfef257a4cae52b32 which I suspects happens when we try to delete the old git hook files. I tried to run the command with and without sudo permissions and without. 

I can confirm that 0.2.0 runs fine!

```
[jiachen@jiachen cadet]$ uname -a
Linux jiachen 4.19.42-1-MANJARO #1 SMP PREEMPT Fri May 10 20:52:43 UTC 2019 x86_64 GNU/Linux
[jiachen@jiachen cadet]$ mix --version
Erlang/OTP 21 [erts-10.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Mix 1.8.1 (compiled with Erlang/OTP 20)
[jiachen@jiachen cadet]$ mix git_hooks.run pre_commit

** (File.Error) could not remove files and directories recursively from "/home/jiachen/Desktop/source-academy/shuming/cadet/_build/dev/lib/git_hooks": permission denied
    (elixir) lib/file.ex:1252: File.rm_rf!/1
    (mix) lib/mix/tasks/deps.compile.ex:66: anonymous fn/4 in Mix.Tasks.Deps.Compile.compile/2
    (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
    (mix) lib/mix/tasks/deps.compile.ex:64: Mix.Tasks.Deps.Compile.compile/2
    (mix) lib/mix/tasks/deps.loadpaths.ex:89: Mix.Tasks.Deps.Loadpaths.deps_check/2
    (mix) lib/mix/tasks/deps.loadpaths.ex:28: Mix.Tasks.Deps.Loadpaths.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
[jiachen@jiachen cadet]$ sudo mix git_hooks.run pre_commit
[sudo] password for jiachen: 
==> git_hooks
Compiling 5 files (.ex)
⚠ Remove old git hook ``

== Compilation error in file lib/git_hooks.ex ==
** (File.Error) could not remove file "/home/jiachen/Desktop/source-academy/shuming/cadet/deps/../.git/hooks": not owner
    (elixir) lib/file.ex:1092: File.rm!/1
    (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:769: Enum.each/2
    lib/mix/tasks/git_hooks/install.ex:40: Mix.Tasks.GitHooks.Install.install/1
    lib/git_hooks.ex:5: (module)
could not compile dependency :git_hooks, "mix compile" failed. You can recompile this dependency with "mix deps.compile git_hooks", update it with "mix deps.update git_hooks" or clean it with "mix deps.clean git_hooks"
[jiachen@jiachen cadet]$ mix git_hooks.run pre_commit
** (File.Error) could not remove files and directories recursively from "/home/jiachen/Desktop/source-academy/shuming/cadet/_build/dev/lib/git_hooks": permission denied
    (elixir) lib/file.ex:1252: File.rm_rf!/1
    (mix) lib/mix/tasks/deps.compile.ex:66: anonymous fn/4 in Mix.Tasks.Deps.Compile.compile/2
    (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
    (mix) lib/mix/tasks/deps.compile.ex:64: Mix.Tasks.Deps.Compile.compile/2
    (mix) lib/mix/tasks/deps.loadpaths.ex:89: Mix.Tasks.Deps.Loadpaths.deps_check/2
    (mix) lib/mix/tasks/deps.loadpaths.ex:28: Mix.Tasks.Deps.Loadpaths.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/task.ex:355: Mix.Task.get_task_or_run/3
```

**Comment by qgadrian** [comment]
Hi @jiachen247 I've made some changes in the git hooks backup code.

Although looks like you have some permission problems... 🤔 

I uploaded a pre-release `0.3.2-pre2` for this, could you please check if the fix works for you?

Cheers!

**Comment by qgadrian** [comment]
Closing due inactivity
